project(
  'relix',
  ['c', 'rust'],
  meson_version: '>=1.8.0',
  default_options: {
    'c_std': 'gnu11',
    'rust_std': '2024',
    'warning_level': '2',
  }
)

rust = import('rust')

cc = meson.get_compiler('c')
rustc = meson.get_compiler('rust')

spin_dep = dependency('spin-0.9-rs')
pci_ids_dep = dependency('pci-ids-0.2-rs')

analyzer = false

add_project_arguments(
  '-fno-pic',
  '-static',
  '-fno-builtin',
  '-ffreestanding',
  '-fno-strict-aliasing',
  '-nostdlib',
  '-Og',
  '-ggdb',
  '-fno-omit-frame-pointer',
  '-nostdinc',
  language: 'c',
)

add_project_link_arguments(
  '-nostdlib',
  language: 'c',
)

# ARCHNOFLAGS
add_project_arguments(
  '-mno-sse', '-mno-red-zone', '-mno-avx', '-mno-avx2', '-mno-mmx', '-mno-80387',
  language: 'c',
)

add_project_arguments(
  '-Wformat', '-Wnull-dereference', '-Warray-bounds', '-Wswitch', '-Wshadow',
  # TODO get rid of this
  '-Wno-unused-parameter', '-Wno-infinite-recursion', '-Wno-pointer-arith', '-Wno-unused', '-Wno-pedantic', '-Wno-sign-compare',
  cc.get_supported_arguments('-Wno-clobbered'),
  language: 'c',
)

add_project_link_arguments(cc.get_supported_link_arguments('-fuse-ld=lld'), language: 'c')

add_project_arguments(cc.get_supported_arguments('-fno-stack-protector'), language: 'c')

if analyzer
  add_project_arguments(
    cc.get_supported_arguments(
      # clang
      '--analyze',
      # gcc
      '-fanalyzer', '-Wno-analyzer-va-arg-type-mismatch',
    ),
    language: 'c'
  )
endif

add_project_arguments(
  '-Ctarget-feature=-avx,-avx2,-sse,-sse2,-sse3,-ssse3,-sse4.1,-sse4.2',
  '-Crelocation-model=static',
  '-Cpanic=abort',
  '-Ccode-model=kernel',
  '-Cno-redzone=true',
  '-Cincremental=true',
  '-Cforce-unwind-tables=n',
  '-Ccodegen-units=1',
  '-Csymbol-mangling-version=v0',
  rustc.get_supported_arguments('-Zfunction-sections=n', checked: 'warn'),
  language: 'rust',
)

kernel_c_args = []

if get_option('debug')
  add_project_arguments(
    '-Cembed-bitcode=n',
    language: 'rust',
  )
  kernel_c_args += ['-D__KERNEL_DEBUG__=1']
else
  add_project_arguments(
    '-Cembed-bitcode=yes',
    language: 'rust',
  )
  kernel_c_args += ['-D__KERNEL_DEBUG__=0']
endif

# Meson compiles assembler files with cc and as such uses the C language.
add_project_arguments(
  cc.get_supported_arguments(
    # -ggdwarf-2
    '-Wa,-divide',
    '--mx86-used-note=no',
  ),
  language: 'c'
)

add_project_arguments(
  '-m64', '-march=x86-64', '-mtls-direct-seg-refs', '-DX86_64=1', '-D__relix__=1',
  language: 'c'
)

add_project_link_arguments(
  cc.get_supported_link_arguments('-fno-pie', '-no-pie', '-nopie'),
  language: 'c'
)

global_include = include_directories('.', 'include')

# CLEAN := $(filter clean, $(MAKECMDGOALS))
#
# IVARS = -Iinclude/ -I.
# # directories
# TOOLSDIR = tools
# BIN = bin
# SYSROOT = sysroot
#
# DIRECTORIES = $(BIN) $(SYSROOT)/$(BIN) $(BIN)/64
#
# default: $(CLEAN)
# 	$(MAKE) $(KERNELDIR)/include/autogenerated/compiler_information.h
# 	$(MAKE) $(DIRECTORIES)
# 	$(MAKE) images
# images: $(BIN)/fs.img $(BIN)/kernel
# $(DIRECTORIES):
# 	mkdir -p $@
#
# include lib/Makefile

subdir('lib')

# include userspace/Makefile

subdir('userspace')
# include kernel/Makefile
#
#
#
# $(KERNELDIR)/include/autogenerated/compiler_information.h:
# 	mkdir -p $(KERNELDIR)/include/autogenerated
# 	printf \
# 	"#pragma once\n \
# 	#define RELIX_COMPILER \"$(shell $(CC) --version | sed -n 1p)\"\n \
# 	#define RELIX_LINKER \"$(shell $(LD) --version | sed -n 1p)\"\n" \
# 		> $(KERNELDIR)/include/autogenerated/compiler_information.h
#
#
# $(BIN)/mkfs: $(TOOLSDIR)/mkfs.c
# 	$(CC) $(LINKER_FLAGS) -Werror -Wall -ggdb -o $@ $^ -I.
#
# # Prevent deletion of intermediate files, e.g. cat.o, after first build, so
# # that disk image changes after first build are persistent until clean.  More
# # details:
# # http://www.gnu.org/software/make/manual/html_node/Chained-Rules.html
# .PRECIOUS: $(BIN)/%.o
#
#
# $(BIN)/fs.img: $(BIN)/mkfs $(UPROGS) bin/kernel
# 	./$(BIN)/mkfs $@ README.md sysroot/test.sh $(wildcard sysroot/etc/*) $(UPROGS)
#
# clean: user_cargo_clean kernel_cargo_clean
# 	@if [ -z "$(BIN)" ]; then exit 1; fi
# 	@if [ "x$(SYSROOT)" = "x" ]; then exit 1; fi
# 	@if [ "x$(KERNELDIR)" = "x" ]; then exit 1; fi
# 	@if [ "x$(BIN)" = "x$$HOME" ]; then exit 1; fi
#
# 	rm -rf \
# 	$(SYSROOT)/bin/* \
# 	$(SYSROOT)/mkfs \
# 	$(KERNELDIR)/include/autogenerated/* \
# 	$(BIN)/* \
# 	iso/kernel
#
# # run in emulators
#
# bochs : fs.img relix.img
# 	if [ ! -e .bochsrc ]; then ln -s dot-bochsrc .bochsrc; fi
# 	bochs -q
#
# # try to generate a unique GDB port
# GDBPORT = $(shell expr `id -u` % 5000 + 25000)
# # QEMU's gdb stub command line changed in 0.11
# QEMUGDB = $(shell if $(QEMU) -help | grep -q '^-gdb'; \
# 	then echo "-gdb tcp::$(GDBPORT)"; \
# 	else echo "-s -p $(GDBPORT)"; fi)
# ifndef CPUS
# CPUS := 2
# endif
# ifndef MEM
# MEM := 224M
# endif
# QEMUOPTS = -drive file=$(BIN)/fs.img,index=1,media=disk,format=raw,if=ide,aio=native,cache.direct=on \
# 					 -enable-kvm -smp cpus=$(CPUS),cores=1,threads=1,sockets=$(CPUS) -m $(MEM) -vga std $(QEMUEXTRA)
#
# ifdef CONSOLE_LOG
# 	QEMUOPTS += -serial mon:stdio
# endif
# ISO = relix
# iso: default
# 	cp $(BIN)/kernel iso/boot/
# 	grub-mkrescue -o $(BIN)/$(ISO).iso iso/
#
# qemu-grub: iso
# 	$(QEMU) -cdrom $(BIN)/$(ISO).iso $(QEMUOPTS)
#
# qemu: qemu-grub
#
# qemu-gdb: iso
# 	$(QEMU) -cdrom $(BIN)/$(ISO).iso $(QEMUOPTS) -S $(QEMUGDB)
# 	@echo "*** Now run 'gdb'." 1>&2
#
# qemu-memfs: relixmemfs.img
# 	$(QEMU) -drive file=$(BIN)/relixmemfs.img,index=0,media=disk,format=raw -smp $(CPUS) -m $(MEM)
#
# .gdbinit: debug/.gdbinit.tmpl
# 	sed "s/localhost:1234/localhost:$(GDBPORT)/" < $^ > $@
#
# format:
# 	@find . -iname *.h -o -iname *.c | xargs clang-format -style=file:.clang-format -i
